service: template-project

provider:
  name: aws
  runtime: nodejs14.x
  stage: prod
  lambdaHashingVersion: 20201221
  timeout: 20
  region: af-south-1
  memorySize: 128
functions:
  app:
    handler: index.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

plugins:
  - serverless-offline
